language: node_js
node_js:
  - "12.2.0"

cache:
  directories:
    - node_modules

script:
  - npm run test:unit && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local-dir: dist
  on:
    branch: master
